sudo: required
language: node_js
node_js:
  - "5.3.0"
services:
  - mongodb
before_install:
  - curl https://install.meteor.com | /bin/sh
  - npm install -g meteorite
before_script:
  - export PATH=$HOME/.meteor:$PATH
